set -g default-terminal "screen-256color"
set -g default-terminal "xterm"
set -g default-terminal "xterm-256color"

set -g default-command "/bin/zsh"

# split windows like vim
# vim's definition of a horizontal/vertical split is reversed from tmux's
bind s split-window -v
bind v split-window -h

# switch window
# bind C-j next-window
# bind C-k previous-window

# move around panes with hjkl, as one would in vim after pressing ctrl-a
bind C-h run-shell -b 'tmux-keep-zoom L'
bind C-j run-shell -b 'tmux-keep-zoom D'
bind C-k run-shell -b 'tmux-keep-zoom U'
bind C-l run-shell -b 'tmux-keep-zoom R'
unbind z
bind z run-shell -b 'tmux-resize-screen'

# vi-style controls for copy mode
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
setw -g mode-keys vi
set -g display-time 1

set -g status 'on'
# set -g status-position top
set -g status-bg 'colour235'
set -g status-justify 'centre'
set -g status-left-length '100'
set -g status-right-length '100'
set -g message-style fg='colour222',bg='colour238'
set -g message-command-style fg='colour222',bg='colour238'
set -g pane-border-style fg='colour238'
set -g pane-active-border-style fg='colour154'
setw -g window-status-activity-style fg='colour154',bg='colour235',none
setw -g window-status-separator ''
setw -g window-status-style fg='colour121',bg='colour235',none
set -g status-left '#[fg=colour232,bg=colour154] #S #[fg=colour154,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #W #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour121,bg=colour235] #(whoami)  #(uptime  | cut -d " " -f 1,2,3) #[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]'
set -g status-right '#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour121,bg=colour235] %r  %a  %Y #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #H #[fg=colour154,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour232,bg=colour154] #(rainbarf --battery --remaining --no-rgb) '
setw -g window-status-format '#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[default] #I  #W #[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=colour235,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #I  #W  #F #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]'
